import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import type { TeamPlayer } from '../api/types'
import StatusMessage from '../components/StatusMessage'

export default function TeamPlayerFormPage() {
  const { teamId, playerId } = useParams(); const navigate = useNavigate(); const edit = Boolean(playerId); const [resolvedTeamId,setResolvedTeamId]=useState(teamId ?? '')
  const [firstName,setFirstName]=useState(''); const [lastName,setLastName]=useState(''); const [displayName,setDisplayName]=useState(''); const [shirtNumber,setShirtNumber]=useState(''); const [position,setPosition]=useState(''); const [active,setActive]=useState(true); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false)
  useEffect(() => { if(edit) api.get<TeamPlayer>(`/team-players/${playerId}`).then(p => { setResolvedTeamId(String(p.teamId)); setFirstName(p.firstName); setLastName(p.lastName); setDisplayName(p.displayName); setShirtNumber(p.shirtNumber == null ? '' : String(p.shirtNumber)); setPosition(p.position ?? ''); setActive(p.active) }).catch(e=>setError(e.message)) },[edit,playerId])
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError(null);try{const body={firstName,lastName,displayName:displayName||null,shirtNumber:shirtNumber===''?null:Number(shirtNumber),position:position||null,active,photoUrl:null};if(edit)await api.put(`/team-players/${playerId}`,body);else await api.post(`/teams/${resolvedTeamId}/players`,body);navigate(`/admin/teams/${resolvedTeamId}/players`)}catch(e){setError(e instanceof ApiError?e.message:'No se pudo guardar el jugador.')}finally{setSaving(false)}}
  const back=`/admin/teams/${resolvedTeamId}/players`; return <div><div className="breadcrumb"><Link to={back}>← Volver a Plantel</Link></div><div className="admin-header"><h1>{edit?'Editar Jugador':'Nuevo Jugador'}</h1></div>{error&&<StatusMessage kind="error" message={error}/>}<form className="form-card" onSubmit={submit}><div className="form-row"><div className="form-field"><label>Nombre</label><input value={firstName} onChange={e=>setFirstName(e.target.value)} required/></div><div className="form-field"><label>Apellido</label><input value={lastName} onChange={e=>setLastName(e.target.value)} required/></div></div><div className="form-field"><label>Nombre visible</label><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Se completa con nombre y apellido"/></div><div className="form-row"><div className="form-field"><label>Número (opcional)</label><input type="number" min="0" max="99" value={shirtNumber} onChange={e=>setShirtNumber(e.target.value)}/></div><div className="form-field"><label>Posición (opcional)</label><input value={position} onChange={e=>setPosition(e.target.value)}/></div></div><label className="checkbox-label"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Jugador activo</label><div className="form-actions"><button className="btn btn-primary" disabled={saving}>{saving?'Guardando...':'Guardar'}</button><Link className="btn btn-secondary" to={back}>Cancelar</Link></div></form></div>
}
